/* ================================================================
   lang-data.js — all language data arrays
   Last updated: 2026-08-23T02:33:53.798Z
   ================================================================ */

const DICT = [
  ["aesh", "prep.", "within: 2D"],
  ["anan", "n.", "object, thing"],
  ["ap", "prep.", "at: 1D; with regards to"],
  ["auz'bleu", "n.", "nostalgia: helplessness from that you cannot return to the past"],
  ["auz'meus", "n.", "language"],
  ["bas", "adj./n.", "cyan: 00fffff"],
  ["bi", "adj.", "small: 2D/3D"],
  ["bleu", "n.", "past: what's before \"now\" on timeline"],
  ["bleut", "mod v.", "[perfects]"],
  ["blip", "pron.", "you: second person singular object"],
  ["blipn", "pron.", "you: second person plural object"],
  ["blop", "pron.", "you: second person singular"],
  ["blopek", "det.", "your: second person singular possessive"],
  ["blopn", "pron.", "you: second person plural"],
  ["blopnek", "det.", "your: second person plural possessive"],
  ["blor", "n.", "permission: pos&0/0 expectation"],
  ["bloret", "mod v.", "is allowed to"],
  ["bomshe", "intj.", "\"you are being too polite\""],
  ["buc", "prep.", "to the front of: 3D, relative to the ground"],
  ["cee", "adj.", "shallow: front-back short"],
  ["ceeven", "adj./n.", "lime: ccff00"],
  ["cor", "adj.", "deep: front-back long"],
  ["dasio", "n.", "math: the field of study"],
  ["deum", "adj./n.", "green: 00ff00"],
  ["eeb", "v.", "go to bed"],
  ["faevois", "n.", "reason: the human-assigned cause of any particular human action"],
  ["faevoiset", "v.", "introspect to find faevoise"],
  ["fas", "adj./n.", "yellow: ffff00"],
  ["flai", "n.", "water"],
  ["fluf", "v.", "have, possess"],
  ["funit", "v.", "happen, take place"],
  ["gal", "det.", "every, any [stresses generality]"],
  ["gee", "adj.", "short: temporally"],
  ["gra", "adj.", "far: spatially, temporally, idea-ly"],
  ["hai", "adj.", "big: 2D/3D"],
  ["haishem", "n.", "haishemi thoughts"],
  ["haishemet", "v.", "be haishemi"],
  ["haishemi", "adj.", "considerate: [person, action] incurs pos to others only achievable by stepping in their shoes"],
  ["hat", "con.", "precedes the focused word in the sentence"],
  ["heush", "adj./n.", "magenta: ff00ff"],
  ["hi", "adj.", "short: 1D"],
  ["hol", "prep.", "above [an object]"],
  ["jeeyeu", "adj./n.", "amber: color of honey (dark, rich yellow)"],
  ["jeu", "adj.", "narrow: horizontally short"],
  ["kif", "n.", "action: a physical/metaphorical movement/decision"],
  ["kifet", "v.", "act: make an action"],
  ["kifi", "adj.", "fast/decisive: kifet fast"],
  ["kotot", "n.", "train of thought: multiple thought points intended to flow logically / in sequence"],
  ["laen", "pron.", "third person singular [default]"],
  ["laena", "pron.", "she: third person singular female human"],
  ["laenek", "det.", "third person singular possessive"],
  ["laenen", "pron.", "they: third person plural"],
  ["laeni", "pron.", "third person singular human [unspecified/other gender]"],
  ["laeno", "pron.", "he: third person singular male human"],
  ["le", "det.", "a: any one of [unspecific]"],
  ["lei", "prep.", "close: spatially, temporally, idea-ly"],
  ["lin", "pron.", "third person singular object"],
  ["lol-", "prep.", "exclusive or [add POE suffix]"],
  ["loo", "adj.", "tall: vertically tall"],
  ["lud", "prep.", "to the left of: any dimension"],
  ["mail", "adj.", "wide: horizontally long"],
  ["mav", "prep.", "to the right of: any dimension"],
  ["meus", "n.", "speech: language sounds"],
  ["meuset", "v.", "speak: emit meus"],
  ["meusi", "adj.", "[person] talkative"],
  ["mi", "pron.", "me: first person singular object"],
  ["mim", "n.", "probability: how possible something is"],
  ["mimet", "mod v.", "possibly"],
  ["mimi", "adj.", "possible: not impossible [0]"],
  ["mo", "pron.", "I: first person singular"],
  ["molek", "det.", "my: first person singular possessive"],
  ["mon", "pron", "first person plural, excluding \"blop\""],
  ["mopn", "pron.", "first person plural, including \"blop\""],
  ["mosh", "abbr.", "=mo she"],
  ["moumet", "mod v.", "allegedly"],
  ["nel", "adj.", "short: vertically short"],
  ["oot", "n.", "place, location"],
  ["oun", "prep.", "in: 3D and temporal"],
  ["ouv", "adj./n.", "light blue: 00aaff"],
  ["qal", "n.", "name"],
  ["qalet", "v.", "is called"],
  ["qoe", "conj.", "before: temporal"],
  ["qon", "adj./n.", "dark blue: 0000ff"],
  ["rinet", "mod v.", "can: has the ability to [physically, mentally]"],
  ["rins", "n.", "ability [physically, mentally]"],
  ["rinsi", "adj.", "able: [person] has many abilities"],
  ["roud", "n.", "seat: where one rodet"],
  ["roudet", "v.", "[human] sit: a physical position where"],
  ["run", "prep.", "below [an object]"],
  ["shau", "det.", "the: for proper nouns"],
  ["she", "v.", "=sher [mo she ⇒ mosh]"],
  ["sher", "v.", "be: has the property (characteristic) that"],
  ["sher", "n.", "time", 1],
  ["sheren", "v.", "=sher [for all plural pronouns]"],
  ["sherm", "v.", "=sher [blop sherm]"],
  ["shert", "v.", "=sher [laen shert]"],
  ["sheudasui", "n.", "reality contortion: the dizziness in perception, common after books or movies"],
  ["shi", "adj.", "fast"],
  ["sol-", "prep.", "inclusive or: 1 or 2 of [add POE suffix]"],
  ["ti", "det.", "the: aforementioned, [there is only one thing based on context]"],
  ["tsi", "prep.", "touching: 2D"],
  ["tu'laoshi", "adj.", "wise: [person] has lots of tulaosh"],
  ["tulaosh", "n.", "wisdom: life lesson"],
  ["tulen", "n.", "knowledge: information or skill from experience or education"],
  ["tulet", "v.", "know [tulen]"],
  ["tuli", "adj.", "knowledgeful: [person] has lots of tulen"],
  ["tulrin", "adj.", "knowable: [tulen] possible to be obtained"],
  ["ul-", "prep.", "and: parallel consideration [add POE suffix]"],
  ["vao", "adj.", "slow"],
  ["vid", "n.", "thought: a user-defined region of the kotot"],
  ["videt", "v.", "think: [human-like, complexity]"],
  ["vidi", "adj.", "anxious: [person] generally too many worried thoughts"],
  ["viis", "n.", "fire"],
  ["vog", "adj./n.", "red: ff0000"],
  ["vuan", "n.", "future: what's after \"now\" on the timeline"],
  ["vuet", "mod v.", "[happening in the future]"],
  ["wou", "adj.", "long: temporally"],
  ["wush", "prep.", "far: spatially, temporally, idea-ly"],
  ["yao", "conj.", "after: temporal"],
  ["zaevois", "q.", "why: what faevois"],
  ["zan", "q.", "what: replaces a noun"],
  ["zau", "adj.", "long: 1D"],
  ["zee", "pron.", "filler pronoun [no possessive]"],
  ["zer", "q.", "when: replaces a time adverb"],
  ["zeut", "prep.", "to the back of: 3D, relative to the ground"],
  ["zoot", "q.", "where: replaces a oot adv."],
];

const ROOTS = [
  ["bi", "small: 2D/3D"],
  ["bleu", "relating to the past"],
  ["cee", "shallow: front-back short"],
  ["cor", "deep: front-back long"],
  ["gee", "short: temporally"],
  ["gra", "far: spatially, temporally, idea-ly"],
  ["hai", "big: 2D/3D"],
  ["hi", "short: 1D"],
  ["i", "[object]"],
  ["jeu", "narrow: horizontally short"],
  ["kif", "act(ion)"],
  ["lei", "close: spatially, temporally, idea-ly"],
  ["loo", "tall: vertically tall"],
  ["mail", "wide: horizontally long"],
  ["meus", "speech"],
  ["ner", "short: vertically short"],
  ["o", "[subject]"],
  ["oot", "place, location"],
  ["qoe", "before: temporal"],
  ["sher", "constant"],
  ["shi", "fast"],
  ["vao", "slow"],
  ["vid", "thought"],
  ["vu", "relating to the future"],
  ["wou", "long: temporally"],
  ["yao", "after: temporal"],
  ["zau", "long: 1D"],
];

const GRAMMAR = [
  "# punctuations",
  "comma: 1. indicate pauses. 2. break long sentences into parts.\nperiod: 1. indicate longer pauses. 2. end a sentence, when the thought is complete.\nspace: 1. separate words. 2. use multiple to indicate pauses duration in writing.\nbrackets []: group things/clauses for clarity\nexclamation mark: exclamations\nquestion mark: questions\nparentheses: indicate comments\nslash and ampersand: abbreviations for lol and ul\ndash: 1. force appending / prepending a suffix / prefix. 2. split long words.\nsemicolon:",
  "# questions",
  "- asked with a raising tone\n- precede with a question teaser\n- no word order change, just substitute in the question word",
  "# imperatives",
  "- the verb suffix -et becomes -shiwa\n- use best judgement when the verb doesn't end in -et\n- sher becomes shiwa",
  "# inflections",
  "- plural: add -il\n- comparative: all adjectives are by definition a comparative\n- superlative: add -oe",
  "# derivation",
  "- substitute with z- to create the question word\n- substitute with w- to create the relative pronoun",
];

const PHONETICS = [
  "# overarching theme",
  "Pronunciation is fully predictable from spelling (like literally every other language other than English). Each letter / double vowel represents one sound.",
  "Consonants at the end of a word is pronounced with no aspiration, unless the next word starts with a vowel, in which case, catenation.",
  "It is forbidden to have two consonants together that involve different parts of the mouth (e.g. b with j). So, if two incompatible consonants join by catenation, the first one is dropped.",
  "All words are stressed on the first syllable unless denoted otherwise in the dictionary (generally, this occurs when there is a prefix, or when the word is so long that each syllable cannot receive a distinct pitch).",
  "# consonants",
  "pronounced like english:\nb, f, g, h, l, m, r, s, sh, v, x, z",
  "c = /ts/\nd = /ɾ/ (alveolar tap)\nj = /ʒ/\nk is less aspirated than English\nn = nasalize any single, short vowels before it\np = /ʔ/ (glottal stop)\nq = /tʃ/\nt = /d/\nw is only used at the start of a distinct syllable\ny = /j/",
  "# vowels",
  "a = /a/\nae = /æ/\nai = /ai/\nau = /ao/\ne = /ə/\nee = /e/\nei = /ei/\neu = /y/\ni = /i/ (not ɪ)\no = /o/\noe = /ø/\noi = /oi/\noo = /o:/\nou = /ou/\nu = /u/",
];

const PHILOSOPHY = [
  "# purpose",
  "Meuvid is, after all, a personal project. I will throw in whatever feature I want, and some of that may solve your communication problems. Much needed words will be coined, and I hope that Meuvid can mayhaps reduce miscommunication and promote good values. And have some fun in the process.",
  "If I had to pick a grander-sounding purpose, I will say that Meuvid is a language designed for humans and all their quirks. One of the big area of attack is politeness and the unsaid, which I will try to remove through formulations of expectations. I also want to define vague concepts precisely so we avoid circular philosophical questions that ultimately depend on language.",
  "# communication > grammar",
  "Yes. You can violate any and all of grammar, as long as you are perfectly sure the same meaning will be conveyed across. Note that grammar in Meuvid is designed to enhance clarity and remove ambiguity. The rules are not arbitrary, so do not violate them for no good reason.",
];

const SECTIONS = [
  ["determiners", [
    ["le"],
    ["ti"],
    ["shau"],
    ["gal"],
  ]],
  ["pronouns", [
    "laen defaults to gender-neutral; only use laeni, etc. when needing to specify gender.",
    "For object form, replace the first vowel with \"i\".",
    ["mo"],
    ["blop"],
    ["laen"],
    ["laeno"],
    ["laena"],
    ["laeni"],
    ["mon"],
    ["mopn"],
    ["blopn"],
    ["laenen"],
  ]],
  ["colors", [
    "primary colors: vog, fas, deum, bas, ouv, qon, heush\nsecondary colors: jeeyeu, ceeven\nnote: purple is a shade of qon or a shade of heush",
    ["vog"],
    ["jeeyeu"],
    ["fas"],
    ["ceeven"],
    ["deum"],
    ["bas"],
    ["ouv"],
    ["qon"],
    ["heush"],
  ]],
  ["spatial relations", [
    ["ap"],
    ["tsi"],
    ["aesh"],
    ["oun"],
    ["hol"],
    ["run"],
    ["lud"],
    ["mav"],
    ["buc"],
    ["zeut"],
    ["lei"],
    ["wush"],
  ]],
  ["sizes", [
    ["hi"],
    ["zau"],
    ["bi"],
    ["hai"],
    ["cee"],
    ["cor"],
    ["jeu"],
    ["mail"],
    ["nel"],
    ["loo"],
  ]],
];

const ROOTS_SECTIONS = [
  ["size", [
    ["bi"],
    ["cee"],
    ["cor"],
    ["hai"],
    ["hi"],
    ["zau"],
    ["jeu"],
    ["mail"],
  ]],
];
