/* ================================================================
   lang-data.js — all language data arrays
   Last updated: 2026-06-16T22:53:28.795Z
   ================================================================ */

const DICT = [
  ["aesh", "prep.", "within: 2D"],
  ["anan", "n.", "object, thing"],
  ["ap", "prep.", "at: 1D; with regards to"],
  ["auz'bleu", "n.", "nostalgia: helplessness from that you cannot return to the past"],
  ["auz'meus", "n.", "language"],
  ["bi", "adj.", "small: 2D/3D"],
  ["bleu", "n.", "past: what's before \"now\" on timeline"],
  ["bleut", "mod v.", "[perfects]"],
  ["blip", "pron.", "you: second person singular object"],
  ["blipn", "pron.", "you: second person plural object"],
  ["blop", "pron.", "you: second person singular"],
  ["blopek", "det.", "your: second person singular possessive"],
  ["blopn", "pron.", "you: second person plural"],
  ["blopnek", "det.", "your: second person plural possessive"],
  ["blor", "n.", "permission: pos&0/0 expectation"],
  ["bloret", "mod v.", "is allowed to"],
  ["cee", "adj.", "shallow: front-back short"],
  ["cor", "adj.", "deep: front-back long"],
  ["flai", "n.", "water"],
  ["fluf", "v.", "have, possess"],
  ["funit", "v.", "happen, take place"],
  ["gal", "det.", "every, any [stresses generality]"],
  ["gee", "adj.", "short: temporally"],
  ["gra", "adj.", "far: spatially, temporally, idea-ly"],
  ["hai", "adj.", "big: 2D/3D"],
  ["haishem", "n.", "haishemi thoughts"],
  ["haishemet", "v.", "be haishemi"],
  ["haishemi", "adj.", "considerate: [person, action] incurs pos to others only achievable by stepping in their shoes"],
  ["hi", "adj.", "short: 1D"],
  ["hol", "prep.", "above [an object]"],
  ["jeu", "adj.", "narrow: horizontally short"],
  ["kif", "n.", "action: a physical/metaphorical movement/decision"],
  ["kifet", "v.", "act: make an action"],
  ["kifi", "adj.", "fast/decisive: kifet fast"],
  ["laen", "pron.", "third person singular [default]"],
  ["laena", "pron.", "she: third person singular female human"],
  ["laenek", "det.", "third person singular possessive"],
  ["laenen", "pron.", "they: third person plural"],
  ["laeni", "pron.", "third person singular human [unspecified/other gender]"],
  ["laeno", "pron.", "he: third person singular male human"],
  ["le", "det.", "a: any one of [unspecific]"],
  ["lei", "prep.", "close: spatially, temporally, idea-ly"],
  ["lin", "pron.", "third person singular object"],
  ["lol-", "prep.", "exclusive or [add POE suffix]"],
  ["loo", "adj.", "tall: vertically tall"],
  ["mail", "adj.", "wide: horizontally long"],
  ["meus", "n.", "speech: language sounds"],
  ["meuset", "v.", "speak: emit meus"],
  ["meusi", "adj.", "[person] talkative"],
  ["mi", "pron.", "me: first person singular object"],
  ["mim", "n.", "probability: how possible something is"],
  ["mimet", "mod v.", "possibly"],
  ["mimi", "adj.", "possible: not impossible [0]"],
  ["mo", "pron.", "I: first person singular"],
  ["molek", "det.", "my: first person singular possessive"],
  ["mon", "pron", "first person plural, excluding \"blop\""],
  ["mopn", "pron.", "first person plural, including \"blop\""],
  ["mosh", "abbr.", "=mo she"],
  ["moumet", "mod v.", "allegedly"],
  ["ner", "adj.", "short: vertically short"],
  ["oot", "n.", "place, location"],
  ["oun", "prep.", "in: 3D and temporal"],
  ["qal", "n.", "name"],
  ["qalet", "v.", "is called"],
  ["qoe", "conj.", "before: temporal"],
  ["rinet", "mod v.", "can: has the ability to [physically, mentally]"],
  ["rins", "n.", "ability [physically, mentally]"],
  ["rinsi", "adj.", "able: [person] has many abilities"],
  ["she", "v.", "=sher [mo she ⇒ mosh]"],
  ["sher", "v.", "be: has the property (characteristic) that"],
  ["sher", "n.", "time", 1],
  ["sheren", "v.", "=sher [for all plural pronouns]"],
  ["sherm", "v.", "=sher [blop sherm]"],
  ["shert", "v.", "=sher [laen shert]"],
  ["shi", "adj.", "fast"],
  ["sol-", "prep.", "inclusive or: 1 or 2 of [add POE suffix]"],
  ["ti", "det.", "the: aforementioned, the one and only [specific]"],
  ["tsi", "prep.", "touching [2D]"],
  ["tu'laoshi", "adj.", "wise: [person] has lots of tulaosh"],
  ["tulaosh", "n.", "wisdom: life lesson"],
  ["tulen", "n.", "knowledge: information or skill from experience or education"],
  ["tulet", "v.", "know [tulen]"],
  ["tuli", "adj.", "knowledgeful: [person] has lots of tulen"],
  ["tulrin", "adj.", "knowable: [tulen] possible to be obtained"],
  ["ul-", "prep.", "and: parallel consideration [add POE suffix]"],
  ["vao", "adj.", "slow"],
  ["vid", "n.", "thought: a user-defined region of the train of thought"],
  ["videt", "v.", "think: [human-like, complexity]"],
  ["vidi", "adj.", "anxious: [person] generally too many worried thoughts"],
  ["viis", "n.", "fire"],
  ["vuan", "n.", "future: what's after \"now\" on the timeline"],
  ["vuet", "mod v.", "[happening in the future]"],
  ["wou", "adj.", "long: temporally"],
  ["yao", "conj.", "after: temporal"],
  ["zan", "q.", "what: replaces a noun"],
  ["zau", "adj.", "long: 1D"],
  ["zee", "pron.", "filler pronoun [no possessive]"],
  ["zer", "q.", "when: replaces a time adverb"],
];

const ROOTS = [
  ["bi", "small: 2D/3D"],
  ["bleu", "relating to the past"],
  ["cee", "shallow: front-back short"],
  ["cor", "deep: front-back long"],
  ["gee", "short: temporally"],
  ["gra", "far: spatially, temporally, idea-ly"],
  ["hai", "big: 2D/3D"],
  ["hi", "short: 1D"],
  ["i", "[object]"],
  ["jeu", "narrow: horizontally short"],
  ["kif", "act(ion)"],
  ["lei", "close: spatially, temporally, idea-ly"],
  ["loo", "tall: vertically tall"],
  ["mail", "wide: horizontally long"],
  ["meus", "speech"],
  ["ner", "short: vertically short"],
  ["o", "[subject]"],
  ["oot", "place, location"],
  ["qoe", "before: temporal"],
  ["sher", "constant"],
  ["shi", "fast"],
  ["vao", "slow"],
  ["vid", "thought"],
  ["vu", "relating to the future"],
  ["wou", "long: temporally"],
  ["yao", "after: temporal"],
  ["zau", "long: 1D"],
];

const GRAMMAR = [
  "# punctuations",
  "comma: 1. indicate pauses. 2. break long sentences into parts.\nperiod: 1. indicate longer pauses. 2. end sentences.\nspace: 1. separate words. 2. use multiple to indicate pauses duration in writing.\nbrackets []: group things/clauses for clarity\nexclamation mark: exclamations\nquestion mark: questions\nparentheses: indicate comments\nslash and ampersand: abbreviations for lol and ul\nsemicolon:\ndash:",
  "# questions",
  "- asked with a raising tone\n- no word order change, just substitute in the question word",
  "# imperatives",
  "- the verb suffix -et becomes -shiwa\n- use best judgement when the verb doesn't end in -et\n- sher becomes shiwa",
  "# comparatives and superlatives",
  "All adjectives are automatically a comparative. For superlative, add -oe.",
];

const PHONETICS = [
  "# overarching theme",
  "Pronunciation is fully predictable from spelling (like literally every other language other than English). Each letter / double vowel represents one sound.",
  "Consonants at the end of a word is pronounced like English (e.g. s ⇒ z, t / d ⇒ glottal stop, etc.).",
  "All words are stressed on the first syllable unless denoted otherwise in the dictionary (generally, this occurs when there is a prefix, or when the word is so long that each syllable cannot receive a distinct pitch).",
  "# consonants",
  "pronounced like english:\nb, d, f, g, h, l, m, r, s, sh, v, x, z",
  "c = /ts/\nj = /dʒ/\nk is less aspirated than English\nn = nasalize any single, short vowels before it\np = /ʔ/\nq = /ch/\nt = alveolar tap, if available\nw is only used at the start of a distinct syllable\ny = /j/",
  "# vowels",
  "a = /a/\nae = /æ/\nai = /ai/\nau = /ao/\ne = /ə/\nee = /e/\nei = /ei/\neu = /y/\ni = /i/ (not ɪ)\no = /o/\noe = /ø/\noi = /oi/\noo = /o:/\nou = /ou/\nu = /u/",
];

const PHILOSOPHY = [
  "# purpose",
  "Meuvid is, after all, a personal project. I will throw in whatever feature I want, and some of that may solve your communication problems. Much needed words will be coined, and I hope that Meuvid can mayhaps reduce miscommunication and promote good values. And have some fun in the process.",
  "If I had to pick a grander-sounding purpose, I will say that Meuvid is a language designed for humans and all their quirks. One of the big area of attack is politeness and the unsaid, which I will try to remove through formulations of expectations.",
  "# communication > grammar",
  "Yes. You can violate any and all of grammar, as long as you are perfectly sure the same meaning will be conveyed across. Note that grammar in Meuvid is designed to enhance clarity and remove ambiguity. The rules are not arbitrary, so do not violate them for no good reason.",
];

const SECTIONS = [
  ["pronouns", [
    "Meuvid pronouns mark person and number; the third person defaults to gender-neutral.",
    ["mo"],
    ["blop"],
    ["laen"],
  ]],
];

const ROOTS_SECTIONS = [];
