/* ================================================================
   lang-data.js — all language data arrays
   Last updated: 2026-09-26T06:49:15.912Z
   ================================================================ */

export const DICT = [
  ["aesh", "prep.", "within: 1D/2D; [+ time range / day, etc.]"],
  ["aik", "adv.", "4/5"],
  ["amar", "n.", "house: a place someone would call home"],
  ["amareesh", "n.", "home: where you feel like you belong"],
  ["anan", "n.", "object, thing"],
  ["ap", "prep.", "at: 0D; with regards to, about; [+ time point]"],
  ["arn", "det.", "next"],
  ["auz'bleu", "n.", "nostalgia: helplessness from that you cannot return to the past"],
  ["auz'fivois", "n.", "contributing factor: an inference; one of the causes"],
  ["auz'meus", "n.", "language"],
  ["baesh", "det.", "former: the earlier-mentioned of the two of smth"],
  ["bai", "prep.", "outside: any dimension"],
  ["baira", "prep.", "out of: any dimension"],
  ["bas", "adj./n.", "cyan: 00fffff"],
  ["beem", "n.", "two"],
  ["ben", "postp.", "denote subject in passive voice"],
  ["bi", "adj.", "small: 2D/3D"],
  ["bish", "det./adv.", "little"],
  ["bito", "n.", "photo: taken with a camera"],
  ["bleu", "n.", "past: what's before \"now\" on timeline"],
  ["bleut", "mod v.", "[perfects]"],
  ["blip", "pron.", "you: second person singular object"],
  ["blipn", "pron.", "you: second person plural object"],
  ["blop", "pron.", "you: second person singular"],
  ["blopek", "det.", "your: second person singular possessive"],
  ["blopn", "pron.", "you: second person plural"],
  ["blopnek", "det.", "your: second person plural possessive"],
  ["blor", "n.", "permission: pos&0/0 expectation"],
  ["bloret", "mod v.", "is allowed to"],
  ["boebele", "n. (pl.)", "a vague reference to the public, the people"],
  ["bomshe", "intj.", "\"you are being too polite\""],
  ["bomve", "n.", "rating: from top to maet"],
  ["bu'hali", "conj.", "although: subordinating plot twist"],
  ["bu'qoe", "conj./prep.", "before: temporal (unrestrictive)"],
  ["bu'yao", "conj./prep.", "after: temporal (unrestrictive)"],
  ["buc", "prep./adv.", "to the front (of): 3D, relative to the ground"],
  ["buesh", "det.", "middle: the middle-mentioned of the three of smth"],
  ["cee", "adj.", "shallow: front-back short"],
  ["ceeven", "adj./n.", "lime: ccff00"],
  ["cish", "adj.", "good for something in the future"],
  ["coe", "n.", "three"],
  ["cor", "adj.", "deep: front-back long"],
  ["dasio", "n.", "math: the field of study"],
  ["deum", "adj./n.", "green: 00ff00"],
  ["duo", "n.", "ten"],
  ["eeb", "v.", "go to bed"],
  ["en", "adv.", "[see grammar en-]"],
  ["eues", "adj.", "unpleasant: experiencing it brings mild, unpleasant emotions (boredom, sadness, anxiety...)"],
  ["eumien", "adj.", "pleasant: experiencing it brings dopamine"],
  ["faevois", "n.", "reason: the human-assigned cause of any particular human action"],
  ["faevoiset", "v.", "introspect to find faevoise"],
  ["fakeu", "adj.", "morally/socially bad: other people disapproves of this"],
  ["fas", "adj./n.", "yellow: ffff00"],
  ["faulo", "prep.", "through: 2D, 3D"],
  ["fe", "adv.", "[see grammer fe-]"],
  ["fe'gof", "adj.", "unfunctional: spoiled, unhealthy, didn't work out..."],
  ["fecish", "adj.", "bad for something in the future"],
  ["fein", "n.", "hundred"],
  ["fivois", "n.", "cause: a mathematical or scientific result. see `auzfivois`."],
  ["flai", "n.", "water"],
  ["fluf", "v.", "have, possess"],
  ["fresa", "adj.", "bad (vague), used in jokes"],
  ["funit", "v.", "happen, take place"],
  ["gal", "det.", "every, any [stresses generality]"],
  ["galan", "pron.", "something: an unspecified object or concept"],
  ["galov", "pron.", "someone: an unspecified person"],
  ["gat", "n.", "thousand"],
  ["gee", "adj.", "short: temporally"],
  ["ger", "intj.", "annoyance"],
  ["gof", "adj.", "functional: not spoiled, healthy, it worked out..."],
  ["gom", "prep.", "as, like: denote similarity"],
  ["gooce", "adv.", "today: from falling asleep last night to falling asleep tonight"],
  ["goocia", "adv.", "tonight: from sunset today to falling asleep"],
  ["gooco", "adv.", "this afternoon: from lunch to sunset today"],
  ["gooqi", "adv.", "this morning: from falling asleep last night to lunch"],
  ["hai", "adj.", "big: 2D/3D"],
  ["haiqu", "n.", "7 days; week: Monday to Sunday"],
  ["haish", "det./adv.", "very: hugely"],
  ["haishem", "n.", "haishemi thoughts"],
  ["haishemet", "v.", "be haishemi"],
  ["haishemi", "adj.", "considerate: [person, action] incurs pos to others only achievable by stepping in their shoes"],
  ["haivon", "n.", "a single weekend day"],
  ["hal-", "prep.", "but, except: not the previous, yes the following"],
  ["hali", "conj.", "but: plot twist"],
  ["hat", "con.", "precedes the focused word in the sentence"],
  ["hej", "n.", "ten thousand"],
  ["heush", "adj./n.", "magenta: ff00ff"],
  ["hi", "adj.", "short: 1D"],
  ["hiu", "prep.", "[+ glv/gln] for: denoting purpose of gln"],
  ["hol", "prep./adv.", "above [an object]; up"],
  ["houm", "prep.", "from: away from gln; the stretch between \"this\" and gln"],
  ["huopa", "adj.", "annoying: experiencing it brings intense, unpleasant emotions (anger, fear...)"],
  ["jee", "pron.", "first declare, then reference a noun clause, commonly an event"],
  ["jeeyeu", "adj./n.", "amber: color of honey (dark, rich yellow)"],
  ["jeu", "adj.", "narrow: horizontally short"],
  ["jisi", "intj.", "doch: disagree with a negative statement with the affirmative"],
  ["jo", "n.", "change, transition"],
  ["joat", "v.", "become: a gradual transition from 0 to x"],
  ["ka", "det.", "that/those: located wush"],
  ["kee", "det.", "this/these: located lei"],
  ["kif", "n.", "action: a physical/metaphorical movement/decision"],
  ["kifet", "v.", "act: make an action"],
  ["kifi", "adj.", "fast/decisive: kifet fast"],
  ["koedun", "adv.", "very"],
  ["kotot", "n.", "train of thought: multiple thought points intended to flow logically / in sequence"],
  ["kuev", "n.", "eight"],
  ["laen", "pron.", "third person singular [default]"],
  ["laena", "pron.", "she: third person singular female human"],
  ["laenek", "det.", "third person singular possessive"],
  ["laenen", "pron.", "they: third person plural"],
  ["laeni", "pron.", "third person singular human [unspecified/other gender]"],
  ["laeno", "pron.", "he: third person singular male human"],
  ["lais", "n.", "hundred thousand"],
  ["laiyak", "n.", "color"],
  ["le", "det.", "a: any one of [unspecific]"],
  ["lei", "prep.", "close: spatially, temporally, idea-ly"],
  ["lin", "pron.", "third person singular object"],
  ["loi", "intj.", "yes: agree with a positive statement with the affirmative"],
  ["lol-", "prep.", "exclusive or [add POE suffix]"],
  ["loli", "conj.", "exclusive or"],
  ["loo", "adj.", "tall: vertically tall"],
  ["lud", "prep./adv.", "to the left (of): any dimension"],
  ["maet", "adv.", "5/5"],
  ["mail", "adj.", "wide: horizontally long"],
  ["mar", "n.", "have mar for gln = like gln"],
  ["maret", "v.", "[+gln] like: prefer"],
  ["mav", "prep./adv.", "to the right (of): any dimension"],
  ["meus", "n.", "speech: language sounds"],
  ["meuset", "v.", "speak: emit meus"],
  ["meusi", "adj.", "[person] talkative"],
  ["mi", "pron.", "me: first person singular object"],
  ["micai", "n.", "degree: °"],
  ["mien", "n.", "seven"],
  ["mim", "n.", "probability: how possible something is"],
  ["mimet", "mod v.", "possibly"],
  ["mimi", "adj.", "possible: not impossible [0]"],
  ["mo", "pron.", "I: first person singular"],
  ["molek", "det.", "my: first person singular possessive"],
  ["mon", "pron", "first person plural, excluding `blop`"],
  ["mopn", "pron.", "first person plural, including `blop`"],
  ["mosh", "abbr.", "=mo she"],
  ["moumet", "mod v.", "allegedly"],
  ["muamet", "mod v.", "seem like"],
  ["nel", "adj.", "short: vertically short"],
  ["nil", "n.", "zero"],
  ["noi", "pron.", "first reference, then declare a noun clause, commonly an event"],
  ["oot", "n.", "place, location"],
  ["oun", "prep.", "in: 3D and temporal"],
  ["ouv", "adj./n.", "light blue: 00aaff"],
  ["qa", "n.", "ten billion"],
  ["qal", "n.", "name"],
  ["qalet", "v.", "is called"],
  ["qaohu", "adj.", "accomplishing: experiencing it brings serotonin"],
  ["qoe", "conj./prep.", "before: temporal (restrictive)"],
  ["qon", "adj./n.", "dark blue: 0000ff"],
  ["quvur", "n.", "weekday"],
  ["reec", "adv.", "2/5"],
  ["reik", "n.", "nine"],
  ["rinet", "mod v.", "can: has the ability to [physically, mentally]"],
  ["rins", "n.", "ability [physically, mentally]"],
  ["rinsi", "adj.", "able: [person] has many abilities"],
  ["roud", "n.", "seat: where one rodet"],
  ["roudet", "v.", "[human] sit: a physical position where"],
  ["run", "prep./adv.", "below [an object]; down"],
  ["se", "prep.", "[+glv] from glv's perspective"],
  ["seez", "n.", "writing: what someone writes"],
  ["seezet", "v.", "write: record down with (digital) ink"],
  ["shakei", "adj.", "morally/socially good: other people approves of this"],
  ["shau", "det.", "the: for proper nouns, special nouns, and properties of special nouns"],
  ["she", "v.", "=sher [mo she ⇒ mosh]"],
  ["she'ragi", "adj.", "carefree: careless [+]"],
  ["sheece", "n.", "day: 24h"],
  ["sheecia", "n.", "night: from sunset to falling asleep"],
  ["sheeco", "n.", "afternoon: from lunch to sunset"],
  ["sheeqi", "n.", "morning: from falling asleep to lunch"],
  ["sher", "v.", "be: strict equal, literally is"],
  ["sher", "n.", "time", 1],
  ["sheren", "v.", "=sher [for all plural pronouns]"],
  ["sherm", "v.", "=sher [blop sherm]"],
  ["shert", "v.", "=sher [laen shert]"],
  ["sheudasui", "n.", "reality contortion: the dizziness in perception, common after books or movies"],
  ["shi", "adj.", "fast"],
  ["sho", "n.", "five"],
  ["soet", "det.", "previous"],
  ["sol-", "prep.", "inclusive or: 1 or 2 of [add POE suffix]"],
  ["soli", "conj.", "inclusive or: 1 or 2 of"],
  ["soneum", "n.", "human: anything that appears like yourself. up to the definition of the speaker"],
  ["soug", "n.", "10^15"],
  ["su", "prep.", "[what's after owns what's before]"],
  ["suvein", "prep.", "by: go next to 0D; along: go along 1D; across: end to end in 2D"],
  ["ti", "det.", "the: aforementioned, [there is only one thing based on context]"],
  ["toiveeja", "n.", "a phenomenon where you truly have an opinion, but the opinion could have been resulted from an ulterior motive"],
  ["top", "adv.", "0/5"],
  ["tsi", "prep.", "touching: 1D/2D"],
  ["tu'laoshi", "adj.", "wise: [person] has lots of tulaosh"],
  ["tulaosh", "n.", "wisdom: life lesson"],
  ["tulen", "n.", "knowledge: information or skill from experience or education"],
  ["tulet", "v.", "know [tulen]"],
  ["tuli", "adj.", "knowledgeful: [person] has lots of tulen"],
  ["tulrin", "adj.", "knowable: [tulen] possible to be obtained"],
  ["turesa", "adj.", "good (vague), used in jokes"],
  ["tus", "n.", "four"],
  ["ugien", "prep.", "into: any dimension"],
  ["ul-", "prep.", "and: parallel consideration [add POE suffix]"],
  ["uli", "conj.", "and: parallel consideration"],
  ["van", "n.", "one"],
  ["vao", "adj.", "slow"],
  ["vid", "n.", "thought: a user-defined region of the kotot"],
  ["videt", "v.", "think: [human-like, complexity]"],
  ["vidi", "adj.", "anxious: [person] generally too many worried thoughts"],
  ["viis", "n.", "fire"],
  ["viotolesh", "adv.", "very"],
  ["vog", "adj./n.", "red: ff0000"],
  ["vouj", "adv.", "3/5"],
  ["voul", "prep.", "over, across: 1D"],
  ["vuan", "n.", "future: what's after \"now\" on the timeline"],
  ["vuet", "mod v.", "[happening in the future]"],
  ["wei", "det.", "latter: the later-mentioned of the two of smth"],
  ["woeseg", "n.", "memory: user-defined slices"],
  ["woi", "intj.", "kinda: loi ulan wu"],
  ["wou", "adj.", "long: temporally"],
  ["wu", "intj.", "no: answer with the negative"],
  ["wush", "prep.", "far: spatially, temporally, idea-ly"],
  ["yao", "conj./prep.", "after: temporal (restrictive)"],
  ["yeu", "adv.", "1/5"],
  ["yi", "prep.", "to: arrival/direction to a place, object, or concept"],
  ["zaevois", "q.", "why: what faevois"],
  ["zakee", "q.", "which: replaces an quantifier of an instance of an object"],
  ["zan", "q.", "what: replaces a noun"],
  ["zau", "adj.", "long: 1D"],
  ["zee", "pron.", "filler pronoun [no possessive]"],
  ["zer", "q.", "when: replaces a time adverb"],
  ["zeut", "prep./adv.", "to the back (of): 3D, relative to the ground"],
  ["zis", "part.", "softens the tone"],
  ["ziv", "n.", "six"],
  ["zoot", "q.", "where: replaces a oot adv."],
];

export const GRAMMAR = [
  { text: "# punctuations", id: "bynsrf0k" },
  { text: "comma: 1. indicate pauses. 2. break long sentences into parts.\nperiod: 1. indicate longer pauses. 2. end a sentence, when the thought is complete.\nspace: 1. separate words. 2. use multiple to indicate pauses duration in writing.\nbrackets []: group things/clauses for clarity\nexclamation mark: exclamations\nquestion mark: questions\nparentheses: indicate comments\nslash and ampersand: abbreviations for lol and ul\ndash: 1. force attaching an affix. 2. split long words.\nsemicolon: juxtapose two or more sentences side by side with no clarification on their inter-relationships", id: "0myrgnuu" },
  { text: "# questions", id: "uxfe8j53" },
  { text: "- asked with a raising tone\n- no word order change, just substitute in the question word, created by <g>z-</g>\n- to convey that <h>the question is rhetorical</h>, use <g>-iza</g>\n- to convey that <h>you have no expectations of the answer</h>, use <g>-oci</g>\n- to convey that <h>this is a confirmation question</h>, use <g>nothing</g>", id: "46cv4tg2" },
  { text: "# imperatives", id: "5x0p5suc" },
  { text: "- replace -et with <g>-shiwa</g>\n- use best judgement when the verb doesn't end in -et\n- sher becomes <g>shiwa</g>", id: "ue767j52" },
  { text: "# adjectives", id: "ywqrmiqn" },
  { text: "- <h>comparative</h>: <g>all adjectives are by definition a comparative</g>\n- <h>superlative</h>: <g>add -oe</g>", id: "7m5ajnfl" },
  { text: "- use <g>-an</g> to <h>use an adjective as a noun, e.g. \"the red one\"</h>\n\tnote: plural inflection is needed: \"the considerate\" => `shau haishemianil`", id: "mpt63qc4" },
  { text: "# inflections", id: "lkhm87nj" },
  { text: "- <h>plural</h>: <g>add -il</g>", id: "6oup2v3b" },
  { text: "- <h>past</h>: <g>change to -eul</g>\n- <h>perfect</h>: <g>change to -ov</g>\n- <h>progressive</h>: <g>change to -eiz</g>\n- <h>passive</h>: <g>change to -am</g>\n- <h>impossibility</h>: <g>change to -ee</g>", id: "c6hnq9b0" },
  { text: "# derivation", id: "yzncyryi" },
  { text: "\"vr.\" means the \"verb root\", which is oftentimes the associated noun.", id: "j1iigu95" },
  { text: "- <g>en-</g>: <h>if the old term was x against 0, then the new term is 0 against x</h>\n- <g>fe-</g>: <h>if the old term was x against 0, then the new term is -x against 0</h>", id: "jwilyzfw" },
  { text: "- <g>ge-</g>: <h>[adj. ­=> vt.] to turn gln into [adj.], to make gln [adj.]</h>", id: "kw52tunn" },
  { text: "- <g>-an</g>: <h>[vr. => n.] the action of doing [v.]\n\tnote: this ≈ English's -tion suffix, NOT -ing.\n\t[adj. => n.] the property related to [adj.]</h>", id: "1scookow" },
  { text: "- <g>-ot</g>: <h>[vr. => adj.] = wan [v.]-am </h>\n- <g>-ia</g>: <h>[vr. => adj.] = wan [v.] glv/n</h>\n- <g>-in</g>: <h>[vr. => adj.] = wan rinam [v.]</h>\n- <g>-or</g>: <h>[n. => adj.] = ap [n.]</h>", id: "hrx1d62j" },
  { text: "- <g>-(e)sh</g>: <h>[adj. => adv.] to use this adjective to modify another, immediately following adjective</h>\n- <g>-li</g>: <h>[adj. => adv.] to use this adjective to modify the sentence (the verb)</h>\n\tnote: can also <g>use adj. directly before a verb</g> to do this.", id: "7lr3t0s5" },
  { text: "# prepositions", id: "m6h0ptp8" },
  { text: "- To <h>use a verb as a noun behind a preposition</h>, you <g>just use the verb without modification, but add -et for the prep. (exception: `noi/jee`)</g>\n- To associate an action with an adj., first say the adj, then `sher-[+et]`, then the action phrase. Or use `noi/jee`.\n- To <h>use prepositions that require a POS suffix</h>, <g>first say it before the first item that you wish to join.\n\te.g. `ul amaril ulan noi shau auzbleu shert ti woesegil`</g>\n   However, if you <h>use prepositions to join two lowest-level terms</h>, then you <g>may use only the prepositions at the junctions, and simply attach -e:\n\te.g. `amaril ule shau auzbleu`</g>", id: "tnybjw4m" },
  { text: "# special verbs", id: "qa7avt00" },
  { text: "- `moumet` is required where applicable.\n- special verb + adj. directly, without `sher`.", id: "gem958xu" },
  { text: "# clauses", id: "8f5i1kjy" },
  { text: "- <g>substitute with w-</g>: <h>the restrictive relative pronoun</h>\n- <g>substitute with bu-</g>: <h>the unrestrictive relative pronoun</h>\n \tnote: use <g>`noi`</g> to create <h>a noun clause, commonly an event</h>\n\tnote: `noi/jee` can be used to <g>create a verb clause as an action</g>, by using <h>verb right after the declaration.</h>", id: "43t04mt1" },
  { text: "The verb can be moved to the end if the clause is sufficiently short.", id: "sp20bxl7" },
  { text: "# general notes", id: "qzodtezj" },
  { text: "`yao vs. buyao (& qoe)`:\n\t- `mo vuet eeb, yao blop seezet galan.`\n\t=> \"I will go to bed, after you write something.\" The stress is on the `yao` clause.\n\t- `mo eebeul, buyao mo seezeul galan.`\n\t=> \"I went to bed after I wrote something.\" The stress is NOT on the `buyao` clause.", id: "wo5kg24f" },
];

export const PHONETICS = [
  { text: "# overarching theme", id: "krt48vjn" },
  { text: "Pronunciation is fully predictable from spelling (like literally every other language other than English). Each letter / double vowel represents one sound.", id: "fwnd2dbi" },
  { text: "Consonants at the end of a word is pronounced with no aspiration, unless the next word starts with a vowel, in which case, catenation.", id: "y9c6make" },
  { text: "It is forbidden to have two consonants together that involve different parts of the mouth (e.g. b with j). So, if two incompatible consonants join by catenation, the first one is dropped.", id: "hi1jjtq9" },
  { text: "All words are stressed on the first syllable unless denoted otherwise in the dictionary (generally, this occurs when there is a prefix, or when the word is so long that each syllable cannot receive a distinct pitch).", id: "gsbljrr5" },
  { text: "# consonants", id: "b0agbmro" },
  { text: "pronounced like english:\nb, f, g, h, l, m, r, s, sh, v, z\nx is not used.", id: "21xvxbep" },
  { text: "c = /ts/\nd = /ɾ/ (alveolar tap)\nj = /ʒ/\nk is less aspirated than English\nn = nasalize any single, short vowels before it\np = /ʔ/ (glottal stop)\nq = /tʃ/\nt = /d/\nw is only used at the start of a distinct syllable\ny = /j/", id: "n43zp5ex" },
  { text: "# vowels", id: "kpf48vuh" },
  { text: "i and u can act as y and w (their approximants).", id: "5z56wl39" },
  { text: "a = /a/\nae = /æ/\nai = /ai/\nau = /ao/\ne = /ə/\nee = /e/\nei = /ei/\neu = /y/\ni = /i/ (not ɪ)\no = /o/\noe = /ø/\noi = /oi/\noo = /o:/\nou = /ou/\nu = /u/", id: "p3khs509" },
];

export const WRITING = [
  { text: "hello world :)", id: "ga4wvtaz" },
];

export const PHILOSOPHY = [
  { text: "# purpose", id: "3kwsxmvc" },
  { text: "Meuvid is, after all, a personal project. I will throw in whatever feature I want, and some of that may solve your communication problems. Much needed words will be coined, and I hope that Meuvid can mayhaps reduce miscommunication and promote good values. And have some fun in the process.", id: "re24msqi" },
  { text: "If I had to pick a grander-sounding purpose, I will say that Meuvid is a language designed for humans and all their quirks. One of the big area of attack is politeness and the unsaid, which I will try to remove through formulations of expectations. I also want to define vague concepts precisely so we avoid circular philosophical questions that ultimately just depended on definitions.", id: "bvicm5lf" },
  { text: "# communication > grammar", id: "cee69n20" },
  { text: "Yes. You can violate any and all of grammar, as long as you are perfectly sure the same meaning will be conveyed across. Note that grammar in Meuvid is designed to enhance clarity and remove ambiguity. The rules are not arbitrary, so do not violate them for no good reason.", id: "7enx19v4" },
];

export const SECTIONS = [
  ["determiners", [
    ["le"],
    ["ti"],
    ["shau"],
    ["gal"],
    ["kee"],
    ["ka"],
    ["baesh"],
    ["wei"],
    ["buesh"],
    ["soet"],
    ["arn"],
  ]],
  ["pronouns", [
    { text: "`laen` defaults to gender-neutral; only use `laeni`, etc. when <b>needing</b> to specify gender.", id: "ycjh0856" },
    { text: "For object form, replace the first vowel with \"i\".\nFor possessives, replace the first vowel with \"er\".", id: "fd1zjvsd" },
    ["mo"],
    ["blop"],
    ["laen"],
    ["laeno"],
    ["laena"],
    ["laeni"],
    ["mon"],
    ["mopn"],
    ["blopn"],
    ["laenen"],
    ["noi"],
    ["jee"],
  ]],
  ["special verbs", [
    ["bleut"],
    ["bloret"],
    ["fluf"],
    ["funit"],
    ["kifet"],
    ["mimet"],
    ["moumet"],
    ["muamet"],
    ["rinet"],
    ["sher"],
    ["vuet"],
    ["joat"],
  ]],
  ["conjunctions", [
    ["uli"],
    ["soli"],
    ["loli"],
    ["hali"],
    ["bu'hali"],
    ["qoe"],
    ["bu'qoe"],
    ["yao"],
    ["bu'yao"],
  ]],
  ["abstract prepositions", [
    ["ben"],
    ["hiu"],
    ["se"],
    ["su"],
    ["yi"],
    ["lol-"],
    ["sol-"],
    ["ul-"],
    ["hal-"],
    ["lei"],
    ["wush"],
    ["gom"],
  ]],
  ["spatial relations", [
    { text: "stationary prepositions:", id: "8azsrx3x" },
    ["ap"],
    ["tsi"],
    ["aesh"],
    ["oun"],
    ["bai"],
    ["hol"],
    ["run"],
    ["lud"],
    ["mav"],
    ["buc"],
    ["zeut"],
    ["lei"],
    ["wush"],
    { text: "dynamic prepositions:", id: "atn86cko" },
    ["yi"],
    ["houm"],
    ["ugien"],
    ["baira"],
    ["voul"],
    ["suvein"],
    ["faulo"],
  ]],
  ["laiyakil", [
    { text: "primary colors: vog, fas, deum, bas, ouv, qon, heush\nsecondary colors: jeeyeu, ceeven\nnote: purple is a shade of qon or a shade of heush", id: "1d48p1h3" },
    ["laiyak"],
    ["vog"],
    ["jeeyeu"],
    ["fas"],
    ["ceeven"],
    ["deum"],
    ["bas"],
    ["ouv"],
    ["qon"],
    ["heush"],
  ]],
  ["sizes", [
    ["hi"],
    ["zau"],
    ["bi"],
    ["hai"],
    ["cee"],
    ["cor"],
    ["jeu"],
    ["mail"],
    ["nel"],
    ["loo"],
  ]],
  ["numbers", [
    { text: "<g>-er</g>: turn a number into <h>a compounder: \"three\" => \"tri\".</h>\n<g>-(e)s</g>: turn a number into <h>its reciprocal: \"three\" => \"(one) third\".</h>\n<g>-or</g>: turn a number into <h>cardinals: \"three\" => \"(the) third\".</h>\n<g>-li</g>: turn a number into <h>an aderb as follows: \"three\" => \"in groups of three\".</h>\n<g>-ersh & -erli</g>: turn a number into <h>an aderb as follows: \"three\" => \"triple\".</h>\n<g>-eret</g>: turn a number into <h>a verb as follows: \"three\" => \"triple\".</h>", id: "nuurpcq5" },
    { text: "When hand signaling a number, binary is used. With palms face outwards, right pinky is 1, left pinky is 512.\nWith palms facing inwards, one can signal numbers as follows with one hand (left most digit is pinky):\n`nil` = 00001\t\t`van` = 00010\t\t`beem` = 00110\n`coe` = 11100\t\t`tus` = 11110\t\t`sho` = 11111\n`ziv` = 10001\t\t`mien` = 10010\t\t`kuev` = 00011\n`reik` = 10011\t\t`duo` = 00000", id: "h4e1fwwc" },
    { text: "e.g. 1371,87934,91823 = vcmvq kmrctl rvkbc", id: "irvlcapl" },
    ["nil"],
    ["van"],
    ["beem"],
    ["coe"],
    ["tus"],
    ["sho"],
    ["ziv"],
    ["mien"],
    ["kuev"],
    ["reik"],
    ["duo"],
    ["fein"],
    ["gat"],
    ["hej"],
    ["lais"],
    ["qa"],
    ["soug"],
  ]],
  ["bomvil", [
    { text: "These are used for precise communications. When one is expressing oneself, e.g. when telling a story to a friend, one may choose to use the collection of words that mean \"very\".", id: "p36uohb9" },
    ["bomve"],
    ["top"],
    ["yeu"],
    ["reec"],
    ["vouj"],
    ["aik"],
    ["maet"],
  ]],
  ["degrees", [
    ["bish"],
    ["haish"],
    ["viotolesh"],
    ["koedun"],
  ]],
  ["shau sher", [
    ["sher", 1],
    { text: "relative time:", id: "p65injj8" },
    ["gooce"],
    ["gooqi"],
    ["gooco"],
    ["goocia"],
    { text: "absolute time:", id: "rxcy487r" },
    { text: "`ap` and `aesh` are used for at/in/on.\nA standalone `quvuril` or `haivonil` denote the collection of weekdays (5 of `quvur`), and weekend, respectively.\nTo use `kee haivonil`, one must be in a weekend themselves.", id: "h150njam" },
    ["sheece"],
    ["sheeqi"],
    ["sheeco"],
    ["sheecia"],
    ["quvur"],
    ["haivon"],
    ["haiqu"],
  ]],
  ["turesa, fresa", [
    ["turesa"],
    ["eumien"],
    ["qaohu"],
    ["shakei"],
    ["cish"],
    ["gof"],
    ["fresa"],
    ["eues"],
    ["huopa"],
    ["fakeu"],
    ["fecish"],
    ["fe'gof"],
  ]],
  ["family", [
    { text: "To express a compound relationship, simply say the nouns back to back.", id: "278nmudk" },
  ]],
  ["particles & discourse markers", [
    ["zis"],
  ]],
];
